//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMovie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppVideoUser
    {
        public int VideoUserID { get; set; }
        public int UserID { get; set; }
        public int VideoID { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppVideo AppVideo { get; set; }
    }
    public class VideoModel
    {
        public VideoModel()
        {
            videos = new List<AppVideo>();
        }
        public int UserID { get; set; }
        public List<AppVideo> videos { get; set; }
    }
    public class UserModel
    {
        public UserModel()
        {
            users = new List<AppUser>();
        }
        public int VideoID { get; set; }
        public List<AppUser> users { get; set; }
    }

}
